# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'CurrencyConverter_RuiCanas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrencyConverter_RuiCanas
  pod 'AFNetworking', '~> 4.0'
  pod 'Kingfisher', '~> 6.0'
end
